Rails.application.routes.draw do
  root 'home#index', as: 'home'
  get 'items/add_page'
  get 'items/trade_page'
  get 'items/sell_page'
  post 'items/add', to: 'items#add'
  post 'items/sell_publish', to: 'items#sell_publish'
  post 'items/trade_publish', to: 'items#trade_publish'
  post 'items/cancel_sell_offer/:id', to: 'items#cancel_sell_offer', as: 'item_cancel_sell_offer'
  post 'items/cancel_trade_offer/:id', to: 'items#cancel_trade_offer', as: 'item_cancel_trade_offer'
  post 'items/buy_item', to: 'items#buy_item', as: 'buy_item'
  post 'items/trade_confirm/:id', to: 'items#trade_confirm', as: 'trade_confirm'
  get 'game_accounts/sell_page'
  get 'game_accounts/link_page'
  post 'game_accounts/link', to: 'game_accounts#link'
  post 'game_accounts/sell_publish', to: 'game_accounts#sell_publish'
  post 'game_accounts/cancel_sell_offer/:id', to: 'game_accounts#cancel_sell_offer', as: 'acc_cancel_sell_offer'
  post 'game_accounts/buy/:id', to: 'game_accounts#buy', as: 'acc_buy'
  post 'users/create', to: 'users#create'
  get 'users/new'
  get 'users/support'
  get 'users/write_request_page'
  post 'users/request_publish', to: 'users#request_publish'
  get 'users/reply_request_page'
  post 'users/reply_publish', to: 'users#reply_publish'
  post 'users/block/:id', to: 'users#block', as: 'user_block'
  post 'users/unblock/:id', to: 'user#unblock', as: 'user_unblock'
  get '/users/profile_settings'
  post 'sessions/create', to: 'sessions#create'
  post 'sessions/destroy', to: 'sessions#destroy'
  get 'sessions/new'
  get 'users/restore_password_page'
  post 'users/restore_password', to: 'users#restore_password'
  post '/users/profile_update', to: 'users#profile_update'
  post '/game_accounts/confirm_acc/:id', to: 'game_accounts#confirm_acc', as: 'confirm_acc'
  get 'users/lots_stats'
  get 'users/users_stats'
  get 'users/:id', to: 'users#profile_page', as: 'show_profile'
  get 'users/inventory/:id', to: 'users#inventory', as: 'show_inventory'
  get 'users/comments/:id', to: 'users#comments', as: 'show_comments'
  get 'users/write_comment_page/:id', to: 'users#write_comment_page', as: 'write_comment_page'
  post 'users/comment_publish', to: 'users#comment_publish'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
